[[headers]]
for = "/static/media/*.woff2"
[headers.values]
cache-control = '''
    public,
	max-age=86400,
	immutable'''

# Redirects for the domain
[[redirects]]
from = "/discord"
to = "https://discord.com/invite/ztz44wG"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/messenger"
to = "https://forms.gle/FzqhVEB54rvTqBgi7"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/facebook"
to = "https://www.facebook.com/groups/bc.cis.club"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/bc_compsci"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/github"
to = "https://github.com/bc-compsci-club"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/surveys/welcome-back"
to = "https://forms.gle/CBMDV1aDVqmVAVrv9"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/surveys/welcome"
to = "https://forms.gle/jbrkMKuqixLS2teHA"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/surveys/meet-the-board"
to = "https://forms.gle/NbWnFkHxFsKQsHYk9"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/contribute/apply"
to = "https://forms.gle/HWNzk4LwP1QVQmn87"
status = 302
headers = {Cache-Control = "public, max-age=0, must-revalidate"}

[[redirects]]
from = "/*"
to = "/"
status = 200

[build]
command = "npm run build"
publish = "build"
